---
title:

---





# 如何捕获异常

```c++
try{
  ......
}
catch(...) {
  ......
}
```





# 栈溢出、爆栈

*   函数中的变量存放在栈中。
*   当向数组中写数据，而下标超过数组容量时，实际写入的地方就会超过数组存储空间，此时就会发生栈溢出。
*   如果函数调用的层数过大，向系统栈压入的数据过多，就会发生爆栈。
*   溢出指栈的下溢，爆栈指栈的上溢。

